services:
  nodequery:
    labels:
      app: nodequery
    build:
      context: .
    scale: 1
    environment:
      - MONGO_URI=${MONGO_URI}
      - REDIS_URI=${REDIS_URI}
    ports:
      - 8080:8080
    volumes:
      - nodequery:/data/python

volumes:
  nodequery:
    driver_opts:
      size: 128Mi