name: Okteto

on:
  push:
    branches: [ dev ]
    paths-ignore:
      - '.github/workflows/deploy.yml'
      - 'docker-compse.yaml'
      - 'okteto-stack.yml'

jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Build and push
#        id: docker_build
#        uses: docker/build-push-action@v4
#        with:
#          push: true
#          platforms: linux/amd64,linux/arm64
#          tags: ghcr.io/a224327780/nodequery:latest
  deploy:
#    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: "Activate Namespace"
        uses: okteto/namespace@latest
        with:
          namespace: atcooc123

      - name: "Trigger the pipeline"
        uses: okteto/pipeline@latest
        with:
          name: nodequery
          timeout: 8m